### ISSUE TITLE
User does not have public profile if the leaderboard has not been refresh

### ISSUE THREAD

**Issue by rakeshok** [moneypot/bustabit-webserver#135]
We can look it to the users table too see if the user exist and the leaderboard has not been refreshed

**Comment by kungfuant** [comment]
Every now and then a new player joins the site and ask why her/his charts are broken and everyone elses work. I think you want to leave a good first impression, so should this be given higher priority?

**Comment by rakeshok** [comment]
If they dont exist in the leaderboard query the users table and if they don't exist display a message telling the user the profile will be available on x time

**Comment by RHavar** [comment]
Done
