### ISSUE TITLE
 Strategy feature disabling itself

### ISSUE THREAD

**Issue by RHavar** [moneypot/bustabit-webserver#163]
Report from user:
---
The Strategy feature will disable itself when switching from the game's tab to another tab. The game was working for quite a while in the background until I noticed I had to keep on going back in to click Run. Here's my browser details: Using Google Chrome on Chromium OS Version 40.0.2214.114 (64-bit) Platform 6457.94.0 (Official Build) stable-channel parrot Firmware Google_Parrot.2685.37.0 UA string: Mozilla/5.0 (X11; CrOS x86_64 6457.94.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.114 Safari/537.36

**Comment by rakeshok** [comment]
Test this

**Comment by rakeshok** [comment]
Haven't been reported more than once, provably the script disable itself
