### ISSUE TITLE
value.username is empty after reconnect

### ISSUE THREAD

**Issue by RHavar** [moneypot/bustabit-webserver#200]
engine.on('game_started', function(data) {
	console.log('------------------------------------------------------');
	console.log(data);
    for(var username in data) {
		var value = data[username];
		console.log('   ', username, value.username, value);
	}
});

**Comment by rakeshok** [comment]
https://github.com/moneypot/bustabit-webserver/commit/edd6f9f156d9c8a08ab8c39526768a75ad5c7541
