### ISSUE TITLE
Cashout was not working

### ISSUE THREAD

**Issue by RHavar** [moneypot/bustabit-webserver#224]
When joining a game really late, a user got into a state where the cashout button was grey, counting, but wasn't letting him cashout

**Comment by rakeshok** [comment]
We need more info, looks pretty hard to happen, but its possible to reproduce it if you lose the internet connection after game_started then try to cash out and never receive the response from the server that you cashed out

**Comment by RHavar** [comment]
Closing as appears to have been caused by client side internation connection issue
