### ISSUE TITLE
Postgres Error when running schema.sql

### ISSUE THREAD

**Issue by ascension** [moneypot/bustabit-webserver#240]
I am getting these errors when trying to run the schema.sql script:
- psql:src/server/schema.sql:542: ERROR:  language "plv8" does not exist
- psql:src/server/schema.sql:546: ERROR:  function plays_users_stats_trigger() does not exist

**Comment by RHavar** [comment]
Can you try running:

`CREATE EXTENSION plv8;`

in your database before hand? That should enable v8 for this
