### ISSUE TITLE
Can't login in mobile

### ISSUE THREAD

**Issue by RHavar** [moneypot/bustabit-webserver#242]
20:30 Winmillion: @Ryan cant get into the website through phone, when i try to solve the google captcha it goes below my screen to click verify(doesnt let me scroll down) and 1/3 of the images dont show
20:30 Ryan: what's the phone you use?
20:30 Winmillion: xperia m

**Comment by rakeshok** [comment]
Need an xperia m to try, could not reproduce :/

**Comment by rakeshok** [comment]
Ill check on an small phone
